"use client";
import Link from "next/link";
import { unstable_rethrow } from "next/navigation";
import { useActionState, useRef, useState } from "react";
import { mutateUniversityCatalogAction } from "@/lib/platform-university-catalog-actions";
import { UNIVERSITY_LEVELS, UNIVERSITY_LEVEL_LABELS, parseUniversityContent, type UniversityActionState, type UniversityContent, type UniversityIntake, type UniversityLevel, type UniversityProgram } from "@/lib/platform-university-catalog";

const input = "mt-1 min-h-11 w-full rounded-ctl border border-border bg-surface px-3 py-2 text-sm text-fg disabled:opacity-70";
const button = "inline-flex min-h-11 items-center justify-center rounded-ctl border border-border px-4 py-2 text-sm font-medium disabled:cursor-not-allowed disabled:opacity-50";
const messages: Partial<Record<UniversityActionState["status"], string>> = {
  invalid: "Проверьте обязательные поля, ссылки и даты. Карточка не сохранена.", forbidden: "Нет действующего доступа Admin. Обновите страницу или войдите снова.",
  stale: "Опубликованная версия уже изменилась. Откройте актуальную карточку и перенесите нужные изменения; старую версию нельзя перезаписать.", request_conflict: "Этот запрос уже использован с другим содержимым. Перезагрузите актуальную карточку перед новой попыткой.",
  unavailable: "Ответ сервера не подтверждён. Поля временно заблокированы: повторите тот же запрос или проверьте список черновиков. Не создавайте дубликат.",
};
const initial = (requestId: string): UniversityActionState => ({ status: "idle", requestId, draftId: null, institutionId: null });
/** An uncertain transport result keeps the exact intent for a safe retry. */
function useUniversityAction(requestId: string) {
  const pendingForm = useRef<FormData | null>(null);
  return useActionState(async (previous: UniversityActionState, form: FormData): Promise<UniversityActionState> => {
    const exactForm = pendingForm.current ?? form;
    pendingForm.current = exactForm;
    try {
      const state = await mutateUniversityCatalogAction(previous, exactForm);
      if (state.status !== "unavailable") pendingForm.current = null;
      return state;
    } catch (error) {
      unstable_rethrow(error);
      return { status: "unavailable", requestId, draftId: null, institutionId: null };
    }
  }, initial(requestId));
}
const optional = (value: string) => value.trim() || null;
function TextField({ label, value, change, max = 300, type = "text", required = false, readOnly = false }: { label: string; value: string | null; change: (value: string) => void; max?: number; type?: string; required?: boolean; readOnly?: boolean }) {
  return <label className="block text-sm text-fg-2">{label}<input type={type} value={value ?? ""} onChange={(event) => change(event.target.value)} className={input} maxLength={max} required={required} readOnly={readOnly} /></label>;
}
function LongField({ label, value, change, max, required = false }: { label: string; value: string; change: (value: string) => void; max: number; required?: boolean }) {
  return <label className="block text-sm text-fg-2">{label}<textarea value={value} onChange={(event) => change(event.target.value.replace(/[\r\n]+/g, " "))} className={`${input} min-h-24`} maxLength={max} rows={3} required={required} /></label>;
}
function IntakeEditor({ intake, change, remove }: { intake: UniversityIntake; change: (value: UniversityIntake) => void; remove: () => void }) {
  const field = <K extends keyof UniversityIntake>(key: K, value: UniversityIntake[K]) => change({ ...intake, [key]: value });
  return <div className="space-y-3 rounded-ctl border border-border p-4"><TextField label="Название набора" value={intake.label} change={(v) => field("label", v)} max={200} required /><div className="grid gap-3 sm:grid-cols-2"><TextField label="Дата начала, если известна" value={intake.startDate} change={(v) => { const date = optional(v); change({ ...intake, startDate: date, startMonth: date ? date.slice(0, 7) : intake.startMonth }); }} type="date" /><TextField label="Или только месяц начала" value={intake.startMonth} change={(v) => field("startMonth", optional(v))} type="month" readOnly={intake.startDate !== null} /><TextField label="Срок подачи, если опубликован" value={intake.applicationDeadline} change={(v) => field("applicationDeadline", optional(v))} type="date" /><TextField label="Точное время закрытия, если опубликовано" value={intake.deadlineTime} change={(v) => field("deadlineTime", optional(v))} type="time" /><TextField label="Часовой пояс срока — например Asia/Shanghai" value={intake.timezone} change={(v) => field("timezone", optional(v))} max={100} /><label className="text-sm text-fg-2">Статус по источнику<select className={input} value={intake.status} onChange={(event) => field("status", event.target.value as UniversityIntake["status"])}><option value="unknown">Нужно уточнить</option><option value="announced">Набор объявлен</option><option value="open">Открыт по данным источника</option><option value="closed">Закрыт</option><option value="needs_reconfirmation">Есть расхождение — подтвердить дату</option></select></label></div><LongField label="Оговорки по набору" value={intake.note} change={(v) => field("note", v)} max={1000} /><TextField label="Официальный источник срока (https)" value={intake.sourceUrl} change={(v) => field("sourceUrl", v)} type="url" max={1000} required /><TextField label="Когда проверен этот источник" value={intake.verifiedOn} change={(v) => field("verifiedOn", v)} type="date" required /><button type="button" className={button} onClick={remove}>Убрать набор из новой версии</button></div>;
}
function ProgramEditor({ program, change, remove, today }: { program: UniversityProgram; change: (value: UniversityProgram) => void; remove: (() => void) | null; today: string }) {
  const field = <K extends keyof UniversityProgram>(key: K, value: UniversityProgram[K]) => change({ ...program, [key]: value });
  return <details open className="rounded-card border border-border bg-surface p-4"><summary className="min-h-11 cursor-pointer py-2 font-medium text-fg">{program.title || "Новая программа"}</summary><div className="mt-3 space-y-4"><TextField label="Название программы" value={program.title} change={(v) => field("title", v)} required /><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-fg-2">Уровень<select className={input} value={program.level} onChange={(event) => field("level", event.target.value as UniversityLevel)}>{UNIVERSITY_LEVELS.map((level) => <option key={level} value={level}>{UNIVERSITY_LEVEL_LABELS[level]}</option>)}</select></label><TextField label="Длительность, если известна" value={program.duration} change={(v) => field("duration", optional(v))} max={150} /><TextField label="Язык обучения, если подтверждён" value={program.language} change={(v) => field("language", optional(v))} max={100} /></div><LongField label="Кратко о программе" value={program.summary} change={(v) => field("summary", v)} max={1200} /><TextField label="Официальная страница программы (https)" value={program.sourceUrl} change={(v) => field("sourceUrl", v)} type="url" max={1000} required /><div className="space-y-3"><h3 className="font-medium text-fg">Наборы</h3>{program.intakes.map((intake, index) => <IntakeEditor key={index} intake={intake} change={(updated) => field("intakes", program.intakes.map((item, i) => i === index ? updated : item))} remove={() => field("intakes", program.intakes.filter((_, i) => i !== index))} />)}{program.intakes.length < 12 ? <button type="button" className={button} onClick={() => field("intakes", [...program.intakes, { label: "", startDate: null, startMonth: null, applicationDeadline: null, deadlineTime: null, timezone: null, status: "unknown", note: "", sourceUrl: program.sourceUrl, verifiedOn: today }])}>Добавить набор</button> : null}</div>{remove ? <button type="button" className={button} onClick={remove}>Убрать программу из новой версии</button> : null}</div></details>;
}
export function UniversityEditor({ content: seed, institutionId, baseVersion, requestId, today }: { content: UniversityContent; institutionId: string | null; baseVersion: number; requestId: string; today: string }) {
  const [content, setContent] = useState(seed), [reason, setReason] = useState("Проверка официальных источников для публичного каталога"), [validation, setValidation] = useState(false);
  const [state, action, pending] = useUniversityAction(requestId);
  const successful = state.status === "saved";
  const terminal = ["stale", "request_conflict", "forbidden"].includes(state.status);
  const frozen = pending || state.status === "unavailable" || successful || terminal;
  const field = <K extends keyof UniversityContent>(key: K, value: UniversityContent[K]) => setContent({ ...content, [key]: value });
  if (successful && state.draftId) return <section role="status" className="space-y-3 rounded-card border border-border bg-surface p-5"><h2 className="text-lg font-semibold text-fg">Версия сохранена на проверку</h2><p className="text-sm text-fg-2">Студенты её ещё не видят. Откройте предпросмотр, сверьте все источники и подтвердите публикацию.</p><Link className={button} href={`/v3/universities/manage?draft=${state.draftId}`}>Проверить и опубликовать</Link></section>;
  return <form action={action} onSubmit={(event) => { if (!parseUniversityContent(content) || !reason.trim()) { event.preventDefault(); setValidation(true); } }} className="space-y-5" aria-busy={pending}>
    <input type="hidden" name="operation" value="stage" /><input type="hidden" name="request_id" value={requestId} /><input type="hidden" name="institution_id" value={institutionId ?? ""} /><input type="hidden" name="base_version" value={baseVersion} /><input type="hidden" name="content" value={JSON.stringify(content)} /><input type="hidden" name="reason" value={reason} /><input type="hidden" name="draft_id" value="" /><input type="hidden" name="confirmed" value="" />
    <p className="text-sm leading-6 text-fg-2">Все поля карточки после публикации видны студентам. Не добавляйте персональные данные, внутренние условия, цены без подтверждения или обещания поступления. Неизвестные даты оставляйте пустыми.</p>
    <fieldset disabled={frozen} className="space-y-5"><legend className="sr-only">Сведения о вузе</legend><section className="space-y-4 rounded-card border border-border bg-surface p-5"><h2 className="font-semibold text-fg">Университет</h2><TextField label="Официальное название" value={content.name} change={(v) => field("name", v)} required readOnly={institutionId !== null} /><div className="grid gap-3 sm:grid-cols-2"><TextField label="Код страны — CN, MY или другой ISO-код" value={content.country} change={(v) => field("country", v.toUpperCase())} max={2} required readOnly={institutionId !== null} /><TextField label="Город, если подтверждён" value={content.city} change={(v) => field("city", optional(v))} max={200} readOnly={institutionId !== null} /></div>{institutionId ? <p className="text-xs text-fg-3">Утверждённая идентичность вуза сохраняется. Здесь обновляются публичное описание, программы и даты.</p> : null}<LongField label="Описание для студента" value={content.overview} change={(v) => field("overview", v)} max={1200} required /><TextField label="Официальный сайт (https)" value={content.websiteUrl} change={(v) => field("websiteUrl", v)} max={1000} type="url" required /><TextField label="Основной источник карточки (https)" value={content.sourceUrl} change={(v) => field("sourceUrl", v)} max={1000} type="url" required /><TextField label="Дата проверки источников" value={content.verifiedOn} change={(v) => field("verifiedOn", v)} type="date" required /><LongField label="Что студенту важно уточнить" value={content.notes} change={(v) => field("notes", v)} max={1500} /><p className="text-xs text-fg-3">Фотографии добавляются только из отдельно проверенной библиотеки с указанным источником и условиями использования. Новая карточка может быть без фото.</p></section>
    <section className="space-y-4"><h2 className="font-semibold text-fg">Программы ({content.programs.length})</h2>{content.programs.map((program, index) => <ProgramEditor key={program.id} program={program} today={today} change={(updated) => field("programs", content.programs.map((item, i) => i === index ? updated : item))} remove={content.programs.length > 1 ? () => field("programs", content.programs.filter((_, i) => i !== index)) : null} />)}{content.programs.length < 30 ? <button className={button} type="button" onClick={() => field("programs", [...content.programs, { id: `program-${crypto.randomUUID()}`, title: "", level: "bachelor", duration: null, language: null, summary: "", sourceUrl: content.sourceUrl, intakes: [] }])}>Добавить программу</button> : null}</section><LongField label="Причина публикации или изменения (для Admin)" value={reason} change={setReason} max={500} required /></fieldset>
    {validation ? <p role="alert" className="text-sm text-danger">Проверьте ссылки HTTPS, обязательные поля и даты. Для точного времени срока нужен часовой пояс; месяц должен совпадать с датой начала.</p> : null}{messages[state.status] ? <p role="alert" className="text-sm text-danger">{messages[state.status]}</p> : null}
    <div className="flex flex-wrap gap-3"><button className={`${button} bg-accent text-on-accent`} disabled={pending || terminal}>{pending ? "Сохраняем…" : state.status === "unavailable" ? "Повторить тот же запрос" : "Сохранить на проверку"}</button><Link className={button} href="/v3/universities/manage">К списку черновиков</Link></div>
  </form>;
}
export function UniversityReviewForm({ draftId, requestId }: { draftId: string; requestId: string }) {
  const [decision, setDecision] = useState("publish"), [confirmed, setConfirmed] = useState(false);
  const [state, action, pending] = useUniversityAction(requestId);
  const done = ["published", "rejected"].includes(state.status), terminal = ["stale", "request_conflict", "forbidden"].includes(state.status), frozen = pending || done || terminal || state.status === "unavailable";
  return <form action={action} className="space-y-4 rounded-card border border-border bg-surface p-5" aria-busy={pending}>
    <input type="hidden" name="operation" value={decision} /><input type="hidden" name="request_id" value={requestId} /><input type="hidden" name="institution_id" value="" /><input type="hidden" name="base_version" value="" /><input type="hidden" name="content" value="" /><input type="hidden" name="reason" value="" /><input type="hidden" name="draft_id" value={draftId} /><input type="hidden" name="confirmed" value={confirmed ? "yes" : ""} />
    <h2 className="text-lg font-semibold text-fg">Решение Admin</h2><fieldset disabled={frozen} className="space-y-3"><legend className="sr-only">Проверка источников</legend><label className="text-sm text-fg-2">Что сделать<select className={input} value={decision} onChange={(event) => setDecision(event.target.value)}><option value="publish">Опубликовать эту версию</option><option value="reject">Отклонить черновик</option></select></label><label className="flex min-h-11 items-start gap-3 text-sm leading-6 text-fg"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} className="mt-1.5 size-4" />{decision === "publish" ? "Я проверил официальные источники, сроки и публичность всех полей. Подтверждаю показ этой версии студентам." : "Подтверждаю отклонение. Эта версия не будет показана студентам; опубликованная карточка останется без изменений."}</label></fieldset>
    {done ? <div role="status"><p className="font-medium text-fg">{state.status === "published" ? "Версия опубликована" : "Черновик отклонён"}</p><Link className={`${button} mt-3`} href={state.institutionId ? `/v3/universities/${state.institutionId}` : "/v3/universities/manage"}>Открыть результат</Link></div> : <><button className={`${button} bg-accent text-on-accent`} disabled={pending || terminal || !confirmed}>{pending ? "Подтверждаем…" : state.status === "unavailable" ? "Повторить тот же запрос" : "Подтвердить решение"}</button>{messages[state.status] ? <p role="alert" className="text-sm text-danger">{messages[state.status]}</p> : null}</>}
  </form>;
}
