import type { Locale } from "@/lib/i18n-data";

const ru = {
  portalName: "Кабинет студента",
  skipToContent: "Перейти к содержимому",
  navigation: "Навигация кабинета",
  home: "Главная",
  documents: "Документы",
  applications: "Заявки",
  visa: "Виза",
  payments: "Оплаты",
  messages: "Сообщения",
  team: "Моя команда",
  notifications: "Уведомления",
  profile: "Профиль",
  more: "Ещё",
  moreNavigation: "Другие разделы",
  closeMoreNavigation: "Закрыть другие разделы",
  language: "Язык интерфейса",
  signOut: "Выйти",
  openNotifications: "Открыть уведомления",
  notificationCount: "непрочитанных обновлений",
  homeTitle: "Главная",
  homeDescription: "Ваш путь поступления, ближайший шаг и связь с командой EVO.",
  progressLabel: "Ваш прогресс поступления",
  stageLabel: "Этап",
  nextAction: "Следующее действие",
  noUrgentAction: "Срочных действий нет",
  noUrgentActionBody: "Команда обновит кабинет, когда появится следующий шаг.",
  due: "Срок",
  urgent: "Срочно",
  warning: "Важно",
  normal: "По плану",
  journey: "Путь поступления",
  quickLinks: "Быстрый доступ",
  caseHighlights: "Важное по делу",
  latestUpdate: "Последнее обновление",
  noUpdates: "Команда ещё не публиковала обновлений.",
  supportTeam: "Моя команда",
  write: "Написать",
  viewAll: "Открыть всё",
  documentsTitle: "Документы",
  documentsDescription: "Статусы документов и комментарии команды по вашему делу.",
  documentReadiness: "Готовность",
  accepted: "Принято",
  inReview: "На проверке",
  needsAction: "Требует внимания",
  curatorComment: "Комментарий команды",
  updated: "Обновлено",
  noDocumentsTitle: "Документов пока нет",
  noDocumentsBody: "Когда команда сформирует ваш список, он появится здесь.",
  uploadUnavailableTitle: "Загрузка в кабинете пока недоступна",
  uploadUnavailableBody:
    "В этой версии кабинета нет защищённой загрузки или повторной отправки файлов. Не передавайте паспорт и другие чувствительные документы через обычный чат — уточните у куратора согласованный безопасный канал.",
  requestDocumentHelp: "Уточнить у команды",
  applicationsTitle: "Заявки",
  applicationsDescription: "Текущие подачи в университеты, дедлайны и решения.",
  deadline: "Дедлайн",
  program: "Программа",
  degree: "Уровень",
  country: "Страна",
  notes: "Комментарий",
  noApplicationsTitle: "Заявок пока нет",
  noApplicationsBody: "Согласованные университеты появятся после подготовки стратегии подачи.",
  applicationReadOnlyTitle: "Статусы обновляет команда EVO",
  applicationReadOnlyBody:
    "Кабинет показывает данные из вашего операционного дела. Отправка заявки и изменение решения здесь недоступны.",
  messagesTitle: "Сообщения",
  messagesDescription: "Обновления по вашему делу, опубликованные командой EVO.",
  updateFeed: "Лента обновлений",
  unread: "Новое",
  read: "Просмотрено",
  noMessagesTitle: "Сообщений пока нет",
  noMessagesBody: "Новые комментарии команды появятся здесь.",
  sendingUnavailableTitle: "Отправка сообщений из кабинета не подключена",
  sendingUnavailableBody:
    "Это лента только для чтения. Чтобы задать вопрос, используйте подтверждённые контакты вашей команды ниже.",
  profileTitle: "Профиль",
  profileDescription: "Ваши контактные данные, язык и безопасность доступа.",
  personalData: "Личные данные",
  email: "Эл. почта",
  phone: "Телефон",
  notAssigned: "Не указано",
  security: "Безопасность",
  protectedSession: "Сессия защищена подписанной HTTP-only cookie и доступна только вашей учётной записи.",
  passwordUnavailableTitle: "Смена пароля в кабинете пока недоступна",
  passwordUnavailableBody: "Если вы потеряли доступ или заметили ошибку в данных, обратитесь к команде EVO.",
  profileReadOnlyTitle: "Профиль только для чтения",
  profileReadOnlyBody: "Изменение личных данных в этой версии кабинета не подключено.",
  visaTitle: "Виза",
  visaDescription: "Состояние визового дела, запись и комментарии специалиста.",
  visaCase: "Визовое дело",
  appointment: "Запись",
  visaJourney: "Этапы визы",
  noVisaTitle: "Визовое дело ещё не открыто",
  noVisaBody: "Команда откроет визовый этап, когда ваше дело будет готово.",
  visaHelpTitle: "Нужна помощь по визе?",
  visaHelpBody: "Свяжитесь с куратором. Действия с визовым делом выполняет команда EVO.",
  paymentsTitle: "Оплаты",
  paymentsDescription: "Платежи по сопровождению EVO и их текущий статус.",
  payment: "Платёж",
  amount: "Сумма",
  paidAt: "Оплачен",
  paymentBoundary:
    "Здесь показаны только платежи, записанные в вашем деле. Обучение, проживание, виза, перелёт и другие сторонние расходы не являются оплатой услуг EVO.",
  noPaymentsTitle: "Платежей пока нет",
  noPaymentsBody: "Согласованный график появится здесь после добавления командой.",
  paymentUnavailableTitle: "Онлайн-оплата в кабинете не подключена",
  paymentUnavailableBody:
    "Не вводите реквизиты и не считайте статус подтверждением банковской операции. Для оплаты или сверки свяжитесь с ответственным сотрудником.",
  teamTitle: "Моя команда",
  teamDescription: "Подтверждённые сотрудники, назначенные к вашему делу.",
  manager: "Менеджер",
  curator: "Куратор",
  contactByEmail: "Написать на эл. почту",
  contactByPhone: "Позвонить",
  noTeamTitle: "Команда ещё не назначена",
  noTeamBody: "Когда ответственный сотрудник будет назначен, контакт появится здесь.",
  teamBoundaryTitle: "Контакты берутся из вашего дела",
  teamBoundaryBody: "Кабинет не показывает сотрудников и данные других студентов.",
  notificationsTitle: "Уведомления",
  notificationsDescription: "Непрочитанные обновления и ближайшее действие по вашему делу.",
  attentionNow: "Требует внимания",
  recentNotifications: "Последние обновления",
  noNotificationsTitle: "Новых уведомлений нет",
  noNotificationsBody: "Последние опубликованные обновления всё равно доступны в сообщениях.",
  notificationReadOnlyTitle: "Отметка «прочитано» пока не синхронизируется",
  notificationReadOnlyBody: "Уведомления показаны как записаны в CRM. Кнопки фиктивного подтверждения здесь нет.",
  caseUnavailableTitle: "Дело студента пока не готово",
  caseUnavailableBody:
    "Ваша учётная запись активна, но связанное операционное дело не найдено. Мы не показываем данные другого студента — обратитесь в EVO для безопасной проверки связи.",
  contactSupport: "Связаться с EVO",
  loading: "Загружаем ваш кабинет",
  loadingBody: "Проверяем доступ и получаем только данные вашего дела.",
  errorTitle: "Не удалось открыть раздел",
  errorBody: "Данные не были изменены. Повторите загрузку или вернитесь на главную.",
  retry: "Повторить",
  backHome: "На главную",
  generatedAt: "Данные обновлены",
} as const;

type PortalCopyKey = keyof typeof ru;
type PortalCopy = Record<PortalCopyKey, string>;

const ky: PortalCopy = {
  portalName: "Студенттин кабинети",
  skipToContent: "Мазмунга өтүү",
  navigation: "Кабинеттин навигациясы",
  home: "Башкы бет",
  documents: "Документтер",
  applications: "Арыздар",
  visa: "Виза",
  payments: "Төлөмдөр",
  messages: "Билдирүүлөр",
  team: "Менин командам",
  notifications: "Эскертмелер",
  profile: "Профиль",
  more: "Дагы",
  moreNavigation: "Башка бөлүмдөр",
  closeMoreNavigation: "Башка бөлүмдөрдү жабуу",
  language: "Интерфейстин тили",
  signOut: "Чыгуу",
  openNotifications: "Эскертмелерди ачуу",
  notificationCount: "окулбаган жаңылык",
  homeTitle: "Башкы бет",
  homeDescription: "Тапшыруу жолуңуз, кийинки кадам жана EVO командасы менен байланыш.",
  progressLabel: "Сиздин тапшыруу прогрессиңиз",
  stageLabel: "Этап",
  nextAction: "Кийинки аракет",
  noUrgentAction: "Шашылыш аракет жок",
  noUrgentActionBody: "Кийинки кадам даяр болгондо команда кабинетти жаңыртат.",
  due: "Мөөнөт",
  urgent: "Шашылыш",
  warning: "Маанилүү",
  normal: "План боюнча",
  journey: "Тапшыруу жолу",
  quickLinks: "Тез өтүү",
  caseHighlights: "Иш боюнча маанилүү",
  latestUpdate: "Акыркы жаңылык",
  noUpdates: "Команда азырынча жаңылык жарыялай элек.",
  supportTeam: "Менин командам",
  write: "Жазуу",
  viewAll: "Баарын ачуу",
  documentsTitle: "Документтер",
  documentsDescription: "Сиздин ишиңиз боюнча документтердин абалы жана команданын комментарийлери.",
  documentReadiness: "Даярдык",
  accepted: "Кабыл алынды",
  inReview: "Текшерүүдө",
  needsAction: "Көңүл буруу керек",
  curatorComment: "Команданын комментарийи",
  updated: "Жаңыртылды",
  noDocumentsTitle: "Документтер азырынча жок",
  noDocumentsBody: "Команда тизмеңизди түзгөндө ал ушул жерде көрүнөт.",
  uploadUnavailableTitle: "Кабинеттен жүктөө азырынча жеткиликсиз",
  uploadUnavailableBody:
    "Бул версияда файлды коопсуз жүктөө же кайра жөнөтүү жок. Паспортту жана башка купуя документтерди кадимки чат менен жибербеңиз — куратордон макулдашылган коопсуз каналды тактаңыз.",
  requestDocumentHelp: "Командадан тактоо",
  applicationsTitle: "Арыздар",
  applicationsDescription: "Университеттерге учурдагы арыздар, мөөнөттөр жана чечимдер.",
  deadline: "Мөөнөт",
  program: "Программа",
  degree: "Деңгээл",
  country: "Өлкө",
  notes: "Комментарий",
  noApplicationsTitle: "Арыздар азырынча жок",
  noApplicationsBody: "Макулдашылган университеттер тапшыруу стратегиясы даяр болгондо көрүнөт.",
  applicationReadOnlyTitle: "Абалды EVO командасы жаңыртат",
  applicationReadOnlyBody: "Кабинет операциялык ишиңиздеги маалыматты көрсөтөт. Бул жерден арыз жөнөтүү же чечимди өзгөртүү мүмкүн эмес.",
  messagesTitle: "Билдирүүлөр",
  messagesDescription: "EVO командасы ишиңиз боюнча жарыялаган жаңылыктар.",
  updateFeed: "Жаңылыктар лентасы",
  unread: "Жаңы",
  read: "Көрүлдү",
  noMessagesTitle: "Билдирүүлөр азырынча жок",
  noMessagesBody: "Команданын жаңы комментарийлери ушул жерде көрүнөт.",
  sendingUnavailableTitle: "Кабинеттен билдирүү жөнөтүү туташтырылган эмес",
  sendingUnavailableBody: "Бул окуу үчүн гана лента. Суроо берүү үчүн төмөндөгү ырасталган команда байланыштарын колдонуңуз.",
  profileTitle: "Профиль",
  profileDescription: "Байланыш маалыматыңыз, тил жана кирүү коопсуздугу.",
  personalData: "Жеке маалыматтар",
  email: "Эл. почта",
  phone: "Телефон",
  notAssigned: "Көрсөтүлгөн эмес",
  security: "Коопсуздук",
  protectedSession: "Сессия кол коюлган HTTP-only cookie менен корголот жана сиздин аккаунтка гана жеткиликтүү.",
  passwordUnavailableTitle: "Кабинеттен сырсөздү өзгөртүү азырынча жеткиликсиз",
  passwordUnavailableBody: "Кирүү мүмкүнчүлүгүн жоготсоңуз же ката байкасаңыз, EVO командасына кайрылыңыз.",
  profileReadOnlyTitle: "Профиль окуу үчүн гана",
  profileReadOnlyBody: "Бул версияда жеке маалыматтарды өзгөртүү туташтырылган эмес.",
  visaTitle: "Виза",
  visaDescription: "Виза ишинин абалы, жазылуу жана адистин комментарийлери.",
  visaCase: "Виза иши",
  appointment: "Жазылуу",
  visaJourney: "Виза этаптары",
  noVisaTitle: "Виза иши азырынча ачыла элек",
  noVisaBody: "Ишиңиз даяр болгондо команда виза этабын ачат.",
  visaHelpTitle: "Виза боюнча жардам керекпи?",
  visaHelpBody: "Кураторго кайрылыңыз. Виза ишиндеги аракеттерди EVO командасы аткарат.",
  paymentsTitle: "Төлөмдөр",
  paymentsDescription: "EVO коштоосу боюнча төлөмдөр жана алардын учурдагы абалы.",
  payment: "Төлөм",
  amount: "Сумма",
  paidAt: "Төлөндү",
  paymentBoundary:
    "Бул жерде ишиңизге жазылган төлөмдөр гана көрсөтүлөт. Окуу, жашоо, виза, учуу жана башка үчүнчү тарап чыгымдары EVO кызматынын төлөмү эмес.",
  noPaymentsTitle: "Төлөмдөр азырынча жок",
  noPaymentsBody: "Макулдашылган график команда кошкондо ушул жерде көрүнөт.",
  paymentUnavailableTitle: "Кабинеттен онлайн төлөм туташтырылган эмес",
  paymentUnavailableBody:
    "Реквизиттерди киргизбеңиз жана абалды банк операциясынын ырастоосу деп эсептебеңиз. Төлөм же салыштыруу үчүн жооптуу кызматкерге кайрылыңыз.",
  teamTitle: "Менин командам",
  teamDescription: "Сиздин ишке дайындалган ырасталган кызматкерлер.",
  manager: "Менеджер",
  curator: "Куратор",
  contactByEmail: "Эл. почтага жазуу",
  contactByPhone: "Чалуу",
  noTeamTitle: "Команда азырынча дайындала элек",
  noTeamBody: "Жооптуу кызматкер дайындалганда байланыш ушул жерде көрүнөт.",
  teamBoundaryTitle: "Байланыштар сиздин иштен алынат",
  teamBoundaryBody: "Кабинет башка студенттердин кызматкерлерин жана маалыматтарын көрсөтпөйт.",
  notificationsTitle: "Эскертмелер",
  notificationsDescription: "Окулбаган жаңылыктар жана ишиңиз боюнча жакынкы аракет.",
  attentionNow: "Көңүл буруу керек",
  recentNotifications: "Акыркы жаңылыктар",
  noNotificationsTitle: "Жаңы эскертме жок",
  noNotificationsBody: "Акыркы жарыяланган жаңылыктар билдирүүлөрдө жеткиликтүү.",
  notificationReadOnlyTitle: "«Окулду» белгиси азырынча синхрондолбойт",
  notificationReadOnlyBody: "Эскертмелер CRMде кандай жазылса, ошондой көрсөтүлөт. Бул жерде жасалма ырастоо баскычы жок.",
  caseUnavailableTitle: "Студенттин иши азырынча даяр эмес",
  caseUnavailableBody:
    "Аккаунтуңуз активдүү, бирок байланышкан операциялык иш табылган жок. Биз башка студенттин маалыматын көрсөтпөйбүз — байланышты коопсуз текшерүү үчүн EVOго кайрылыңыз.",
  contactSupport: "EVO менен байланышуу",
  loading: "Кабинетиңиз жүктөлүүдө",
  loadingBody: "Кирүү мүмкүнчүлүгүн текшерип, сиздин ишиңиздин гана маалыматын алып жатабыз.",
  errorTitle: "Бөлүмдү ачуу мүмкүн болгон жок",
  errorBody: "Маалымат өзгөртүлгөн жок. Кайра жүктөңүз же башкы бетке кайтыңыз.",
  retry: "Кайра аракет кылуу",
  backHome: "Башкы бетке",
  generatedAt: "Маалымат жаңыртылды",
};

const en: PortalCopy = {
  portalName: "Student Portal",
  skipToContent: "Skip to content",
  navigation: "Portal navigation",
  home: "Home",
  documents: "Documents",
  applications: "Applications",
  visa: "Visa",
  payments: "Payments",
  messages: "Messages",
  team: "My team",
  notifications: "Notifications",
  profile: "Profile",
  more: "More",
  moreNavigation: "More sections",
  closeMoreNavigation: "Close more sections",
  language: "Interface language",
  signOut: "Sign out",
  openNotifications: "Open notifications",
  notificationCount: "unread updates",
  homeTitle: "Home",
  homeDescription: "Your admission journey, next step, and connection to the EVO team.",
  progressLabel: "Your admission progress",
  stageLabel: "Stage",
  nextAction: "Next action",
  noUrgentAction: "No urgent action",
  noUrgentActionBody: "The team will update your portal when the next step is ready.",
  due: "Due",
  urgent: "Urgent",
  warning: "Important",
  normal: "On track",
  journey: "Admission journey",
  quickLinks: "Quick access",
  caseHighlights: "Case highlights",
  latestUpdate: "Latest update",
  noUpdates: "The team has not posted an update yet.",
  supportTeam: "My team",
  write: "Write",
  viewAll: "View all",
  documentsTitle: "Documents",
  documentsDescription: "Document statuses and team comments for your case.",
  documentReadiness: "Readiness",
  accepted: "Accepted",
  inReview: "In review",
  needsAction: "Needs attention",
  curatorComment: "Team comment",
  updated: "Updated",
  noDocumentsTitle: "No documents yet",
  noDocumentsBody: "Your checklist will appear here after the team prepares it.",
  uploadUnavailableTitle: "Portal upload is not available yet",
  uploadUnavailableBody:
    "This portal version has no secure upload or resubmission flow. Do not send passports or other sensitive documents through ordinary chat; ask your curator for the agreed secure channel.",
  requestDocumentHelp: "Ask the team",
  applicationsTitle: "Applications",
  applicationsDescription: "Current university applications, deadlines, and decisions.",
  deadline: "Deadline",
  program: "Program",
  degree: "Degree",
  country: "Country",
  notes: "Comment",
  noApplicationsTitle: "No applications yet",
  noApplicationsBody: "Agreed universities will appear after the application strategy is prepared.",
  applicationReadOnlyTitle: "The EVO team updates these statuses",
  applicationReadOnlyBody:
    "The portal shows data from your operational case. Submitting an application or changing a decision is not available here.",
  messagesTitle: "Messages",
  messagesDescription: "Case updates published by your EVO team.",
  updateFeed: "Update feed",
  unread: "New",
  read: "Viewed",
  noMessagesTitle: "No messages yet",
  noMessagesBody: "New team comments will appear here.",
  sendingUnavailableTitle: "Portal messaging is not connected",
  sendingUnavailableBody: "This is a read-only feed. To ask a question, use your team's confirmed contact details below.",
  profileTitle: "Profile",
  profileDescription: "Your contact details, language, and access security.",
  personalData: "Personal details",
  email: "Email",
  phone: "Phone",
  notAssigned: "Not provided",
  security: "Security",
  protectedSession: "Your session uses a signed HTTP-only cookie and is available only to your account.",
  passwordUnavailableTitle: "Password changes are not available in the portal yet",
  passwordUnavailableBody: "If you lost access or noticed incorrect data, contact the EVO team.",
  profileReadOnlyTitle: "Profile is read-only",
  profileReadOnlyBody: "Editing personal details is not connected in this portal version.",
  visaTitle: "Visa",
  visaDescription: "Visa case status, appointment, and specialist comments.",
  visaCase: "Visa case",
  appointment: "Appointment",
  visaJourney: "Visa stages",
  noVisaTitle: "Your visa case has not been opened yet",
  noVisaBody: "The team will open the visa stage when your case is ready.",
  visaHelpTitle: "Need visa help?",
  visaHelpBody: "Contact your curator. The EVO team performs actions on the visa case.",
  paymentsTitle: "Payments",
  paymentsDescription: "EVO support payments and their current status.",
  payment: "Payment",
  amount: "Amount",
  paidAt: "Paid",
  paymentBoundary:
    "Only payments recorded in your case are shown here. Tuition, accommodation, visa, travel, and other third-party costs are not payments for EVO services.",
  noPaymentsTitle: "No payments yet",
  noPaymentsBody: "The agreed schedule will appear after the team adds it.",
  paymentUnavailableTitle: "Online payment is not connected",
  paymentUnavailableBody:
    "Do not enter payment details or treat the status as bank confirmation. Contact the responsible team member to pay or reconcile a payment.",
  teamTitle: "My team",
  teamDescription: "Confirmed staff assigned to your case.",
  manager: "Manager",
  curator: "Curator",
  contactByEmail: "Send email",
  contactByPhone: "Call",
  noTeamTitle: "Your team has not been assigned yet",
  noTeamBody: "A contact will appear here when the responsible staff member is assigned.",
  teamBoundaryTitle: "Contacts come from your case",
  teamBoundaryBody: "The portal never shows staff assignments or data from other students.",
  notificationsTitle: "Notifications",
  notificationsDescription: "Unread updates and the next action for your case.",
  attentionNow: "Needs attention",
  recentNotifications: "Recent updates",
  noNotificationsTitle: "No new notifications",
  noNotificationsBody: "Recent published updates are still available under Messages.",
  notificationReadOnlyTitle: "Read status does not sync yet",
  notificationReadOnlyBody: "Notifications are shown as recorded in the CRM. There is no fake acknowledgement control here.",
  caseUnavailableTitle: "Your student case is not ready yet",
  caseUnavailableBody:
    "Your account is active, but no linked operational case was found. We do not show another student's data; contact EVO to verify the link safely.",
  contactSupport: "Contact EVO",
  loading: "Loading your portal",
  loadingBody: "We are checking access and retrieving only your case data.",
  errorTitle: "This section could not be opened",
  errorBody: "No data was changed. Try again or return home.",
  retry: "Try again",
  backHome: "Back home",
  generatedAt: "Data updated",
};

const PORTAL_COPY: Record<Locale, PortalCopy> = { ru, ky, en };

export function getPortalCopy(locale: Locale): PortalCopy {
  return PORTAL_COPY[locale];
}

export type { PortalCopy };
